namespace Sudoku.Analytics;

/// <summary>
/// Represents a searcher that can creates <see cref="Step"/> instances for the specified technique.
/// </summary>
/// <param name="priority"><inheritdoc cref="Priority" path="/summary"/></param>
/// <param name="level"><inheritdoc cref="Level" path="/summary"/></param>
/// <param name="runningArea"><inheritdoc cref="RunningArea" path="/summary"/></param>
/// <seealso cref="Step"/>
[TypeImpl(TypeImplFlags.AllEqualityComparisonOperators)]
public abstract partial class StepSearcher(
	int priority,
	int level,
	StepSearcherRunningArea runningArea = StepSearcherRunningArea.Searching | StepSearcherRunningArea.Collecting
) :
	IComparable<StepSearcher>,
	IComparisonOperators<StepSearcher, StepSearcher, bool>,
	IEquatable<StepSearcher>,
	IEqualityOperators<StepSearcher, StepSearcher, bool>,
	IFormattable
{
	/// <summary>
	/// <para>
	/// Indicates the priority value of the current step searcher.
	/// This property is used for sorting multiple <see cref="StepSearcher"/> instances.
	/// </para>
	/// <para>
	/// Please note that the set value cannot be same for different <see cref="StepSearcher"/> types;
	/// otherwise, <see cref="InvalidOperationException"/> will be thrown while comparing with two <see cref="StepSearcher"/>s.
	/// </para>
	/// <para>
	/// This property may be automatically generated by source generator. Therefore, you may not care about implementation of this property.
	/// </para>
	/// </summary>
	public int Priority { get; } = priority;

	/// <summary>
	/// <para>Indicates the level that the current step searcher belongs to.</para>
	/// <para>
	/// This property indicates how difficult the step searcher can be enabled.
	/// </para>
	/// </summary>
	public int Level { get; } = level;

	/// <summary>
	/// <para>Indicates the running area which describes a function where the current step searcher can be invoked.</para>
	/// <para>
	/// By default, the step searcher will support
	/// both <see cref="StepSearcherRunningArea.Searching"/> and <see cref="StepSearcherRunningArea.Collecting"/>.
	/// </para>
	/// </summary>
	public StepSearcherRunningArea RunningArea { get; } = runningArea;

	/// <summary>
	/// Indicates the implementation details of the current step searcher instance.
	/// </summary>
	public StepSearcherMetadataInfo Metadata => new(this, GetType().GetCustomAttribute<StepSearcherAttribute>()!);


	/// <inheritdoc/>
	public sealed override bool Equals([NotNullWhen(true)] object? obj) => Equals(obj as StepSearcher);

	/// <summary>
	/// Determines whether two <see cref="StepSearcher"/> instances hold a same priority value.
	/// </summary>
	/// <param name="other">The other object to be compared.</param>
	/// <returns>A <see cref="bool"/> result indicating that.</returns>
	public bool Equals([NotNullWhen(true)] StepSearcher? other) => other is not null && Priority == other.Priority;

	/// <inheritdoc/>
	public sealed override int GetHashCode() => Priority;

	/// <summary>
	/// Compares priority value of two <see cref="StepSearcher"/> instances, and returns the less one.
	/// </summary>
	/// <param name="other">The other object to be compared.</param>
	/// <returns>An <see cref="int"/> indicating which one is greater.</returns>
	public int CompareTo(StepSearcher? other) => other is null ? -1 : Priority.CompareTo(other.Priority);

	/// <inheritdoc/>
	public sealed override string ToString() => ToString(null);

	/// <inheritdoc cref="IFormattable.ToString(string?, IFormatProvider?)"/>
	public string ToString(IFormatProvider? formatProvider) => Metadata.GetName(formatProvider as CultureInfo);

	/// <summary>
	/// Try to collect all available <see cref="Step"/>s using the current technique rule.
	/// </summary>
	/// <param name="context">
	/// <para>
	/// The analysis context. This argument offers you some elementary data configured or assigned, for the current loop of step searching.
	/// </para>
	/// <para>
	/// All available <see cref="Step"/> results will be stored in property <see cref="StepAnalysisContext.Accumulator"/>
	/// of this argument, if property <see cref="StepAnalysisContext.OnlyFindOne"/> returns <see langword="false"/>;
	/// otherwise, the property won't be used, and this method will return the first found step.
	/// </para>
	/// </param>
	/// <returns>
	/// Returns the first found step. The return value is not <see langword="null"/>
	/// if <paramref name="context"/>.OnlyFindOne equals <see langword="true"/>, and at least one step is found.
	/// If so, the first found step will be returned; otherwise, <see langword="null"/>.
	/// </returns>
	/// <exception cref="WrongStepException">Throws when a wrong step is found.</exception>
	/// <exception cref="PuzzleInvalidException">Throws when a puzzle is invalid (e.g. no solution).</exception>
	/// <exception cref="OperationCanceledException">
	/// Throws when the <see cref="StepAnalysisContext.CancellationToken"/> is requested.
	/// </exception>
	/// <exception cref="NotImplementedException">Throws when a big or small function is not implemented.</exception>
	/// <exception cref="NotSupportedException">Throws when a big or small function is not supported on purpose.</exception>
	/// <seealso cref="Step"/>
	/// <seealso cref="StepAnalysisContext"/>
	protected internal abstract Step? Collect(ref StepAnalysisContext context);

	/// <inheritdoc/>
	string IFormattable.ToString(string? format, IFormatProvider? formatProvider) => ToString(formatProvider);
}
