//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FilteringPropertyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilteringPropertyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Resources.FilteringPropertyResources", typeof(FilteringPropertyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label of house: 0-8 is for block 1 to 9, 9-17 is for row 1 to 9 and 18-26 is for column 1 to 9.
        /// </summary>
        internal static string FullHouseStep_House_Description {
            get {
                return ResourceManager.GetString("FullHouseStep_House_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        internal static string FullHouseStep_House_Name {
            get {
                return ResourceManager.GetString("FullHouseStep_House_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number for empty cells in target house.
        /// </summary>
        internal static string FullHouseStep_Lasting_Description {
            get {
                return ResourceManager.GetString("FullHouseStep_Lasting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasting.
        /// </summary>
        internal static string FullHouseStep_Lasting_Name {
            get {
                return ResourceManager.GetString("FullHouseStep_Lasting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label of house: 0-8 is for block 1 to 9, 9-17 is for row 1 to 9 and 18-26 is for column 1 to 9.
        /// </summary>
        internal static string HiddenSingleStep_House_Description {
            get {
                return ResourceManager.GetString("HiddenSingleStep_House_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        internal static string HiddenSingleStep_House_Name {
            get {
                return ResourceManager.GetString("HiddenSingleStep_House_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number for empty cells in target house.
        /// </summary>
        internal static string HiddenSingleStep_Lasting_Description {
            get {
                return ResourceManager.GetString("HiddenSingleStep_Lasting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasting.
        /// </summary>
        internal static string HiddenSingleStep_Lasting_Name {
            get {
                return ResourceManager.GetString("HiddenSingleStep_Lasting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number for the house with the least number of empty cells.
        /// </summary>
        internal static string NakedSingleStep_Lasting_Description {
            get {
                return ResourceManager.GetString("NakedSingleStep_Lasting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasting.
        /// </summary>
        internal static string NakedSingleStep_Lasting_Name {
            get {
                return ResourceManager.GetString("NakedSingleStep_Lasting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base difficulty.
        /// </summary>
        internal static string Step_BaseDifficulty_Name {
            get {
                return ResourceManager.GetString("Step_BaseDifficulty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique name.
        /// </summary>
        internal static string Step_Code_Name {
            get {
                return ResourceManager.GetString("Step_Code_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique name (only in English).
        /// </summary>
        internal static string Step_EnglishName_Name {
            get {
                return ResourceManager.GetString("Step_EnglishName_Name", resourceCulture);
            }
        }
    }
}
