global using System;
global using System.Collections.Generic;
global using System.Drawing;
global using System.Drawing.Drawing2D;
global using System.Drawing.Imaging;
global using System.Drawing.Text;
global using System.IO;
global using System.Linq;
global using System.Linq.Providers;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.Versioning;
global using Sudoku.Concepts;
global using Sudoku.Concepts.Marshalling;
global using Sudoku.Descriptors;
global using Sudoku.Drawing.Nodes;
global using static System.MathF;
global using static Sudoku.Concepts.ConclusionType;
#if OCR
global using System.ComponentModel;
global using System.Diagnostics.CodeAnalysis;
global using System.Resources;
global using System.Runtime.InteropServices;
global using System.Threading.Tasks;
global using Emgu.CV;
global using Emgu.CV.CvEnum;
global using Emgu.CV.OCR;
global using Emgu.CV.Structure;
global using Emgu.CV.Util;
global using Sudoku.Resources;
#endif
